name: Build SurvieHome (Maven)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build with Maven
        run: mvn -B -ntp -e package

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: SurvieHome
          path: target/*.jar
